### ISSUE TITLE
Multistore: product link is correct but image links to default shop domain

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/sitemap#23] opened 2024-08-08 17:26 UTC
thirty bees version: edge as of today

module version: 4.2.0

![image](https://github.com/user-attachments/assets/f4fc6688-03f4-487d-bcd1-5f326ed6825e)

When using multistore the product URL is correct but the link to it's image points do default shop's domain.

**Comment by getdatakick** [comment] 2024-08-12 07:47
I can't reproduce this, url links points to correct domain.

I think this is misconfiguration issue on your side. Looks like you are using Media server --> make sure you set it correctly for every shop context.

**Comment by therampagerado** [comment] 2024-08-12 10:20
Yes I use media servers but per shop context.

The shop that belongs to this sitemap uses s1.handball..... not the one in the sitemap.

**Comment by getdatakick** [comment] 2024-08-12 10:54
Indeed, this happens when using 'Generate Sitemap' button in module configuration page.

If you use cronjob url for specific shop it works correctly, though.

**Comment by getdatakick** [comment] 2024-08-12 11:01
This is actually a limitation of core. 

Method `Tools::getMediaServer` uses constant `_MEDIA_SERVER_1_` that is initialized once during thirty bees boostrap in`config.inc.php` file.

Even though 'Generate Sitemap' action changes shop contexts for every shop, that does not change these (read only) constants.

**Comment by getdatakick** [comment] 2024-08-12 11:05
I'm closing this issue because it can't be fixed in the module. The fix must be done in core

**Closed as completed by getdatakick** 2024-08-12 11:05 UTC
Labels: bug, wontfix

**Comment by therampagerado** [comment] 2024-08-12 11:07
Thank you for your time!

**Comment by getdatakick** [comment] 2024-08-12 11:49
Thanks for reporting this. It's quite important to be able to generate links for different shop context.

Fix was simple, and is in the bleeding edge already

**Comment by therampagerado** [comment] 2024-08-12 12:10
Thank you, will update asap! :)
